include::../adoc/toc.adoc[]

= 2. 미들웨어/웹서비스

== 2.1 RAID / SSD
=== RAID
[cols="^2,8,^4,^1", %autowidth.stretch]
|===
^| 구분 ^| 설명 ^| 특징 ^| Disk

^| RAID 0
a| * Stripped Disk Array without Fault tolerance
* 분산 저장
| 성능(속도) &uarr; 가용성 &darr; | 2+

^| RAID 1
a| * Mirroring and Duplexing
* 복사 저장
| 성능(속도) &darr; 가용성 &uarr; | 2+

^| RAID 2
a| * Hamming code ECC
* 분산 저장 + Hamming code(bit) Disk (병목)
* Data Disk 수에 따라 Hamming code(bit) Disk 추가
* stem:[2^p >=d + p + 1]
| 성능(속도) &darr; 가용성 &uarr; | 2+

^| RAID 3
a| * Parallel Transfer with parity
* 분산 저장 + Parity(byte) Disk #1개 (병목)#
| 성능(속도) &darr; 가용성 &uarr; | 3+

^| RAID 4
a| * Independent data disks with shared parity disk
* 분산 저장 + Parity(word/_block_) Disk #1개 (병목)#
| 성능(속도) &darr; 가용성 &uarr; | 3+

^| RAID 5
a| * Independent data disks with distributed parity blocks
* Data + Parity(word/_block_) 분산저장 (병목해소)
| 성능(속도) &uarr; 가용성 &uarr; | 3+

^| RAID 6
a| * Independent data disks with two independent distributed parity schemas
* RAID 5 + Parity(word/_block_) 분산 Disk 추가 +
-> Parity 가 2개 (가용성)
| 성능(속도) &uarr; 가용성 &uarr; | 4+

^| RAID 0 + 1
a| * RAID 0 한것을 RAID 1 로 묶음 | 성능(속도) &uarr; 가용성 &darr; | 4+

^| RAID 1 + 0
a| * RAID 1 한것을 RAID 0 로 묶음 | 성능(속도) &uarr; 가용성 &darr; | 4+
|===

=== SSD

== 2.2 네트워크 저장장치
DAS(Direct Attached Storage)::
* SCSI
SAN(Storage Area Network)::
* ??
NAS(Network Attached Storage)::
* TCP/IP
IP Storage::
* ??

=== Backup
전체(full) 백업:: 전체 복사본
차등(differential) 백업:: 마지막 full backup 후 변경 내역 full backup
증분(incremental) 백업:: 이전 백업 후 변경된 데이터만
합성(synthetic) 백업:: 전체 백업과 증분 백업을 합쳐 백업
중복제거(deduplication) 백업:: 동일 데이터 + 메타 데이터

== 2.3 MSA / Server Less
=== MSA
=== Server Less
컨테이너 레지스트리:: 기능 저장소
컨테이너 오케스트레이터:: 컨테이너 운영/관리
마스터 노드:: 운영 환경 관리
워커 노드:: 기능 수행

== 2.4 분산객체
=== 분산객체
[cols="^1,4,^1,^1,^1", %autowidth.stretch]
|===
^| 구분 ^| 설명 ^| 표준 ^| OS ^| 언어

^| DCE
a| * 절차지향 분산환경 표준
^| OSF ^| ? ^| ?

^| CORBA
a| * 분산 걔체 표준
^| OMG ^| ALL ^| ALL

^| DCOM
a| * 원격객체 서비스 지향
^| MS ^| Window ^| ALL

^| RMI
a| Java 분산 객체
^| Oracle ^| ALL(JVM) ^| Java
|===

=== 미들웨어
어플리케이션들을 연결하고, 서로 데이터를 교환 할 수 있도록 하는 소프트웨어

동기식(Synchronous)::
RPC, ORB, OLTP, RDA
비동기식(Asynchronous)::
MQ, MOM

//==
==== 메시지 처리 방식
* Fire & Forget : 쏘고 몰랑~~
* Publish & Subscript : 쐈으니 받아가
* Routing : 차례대로 전달
* Callback : 받았으면 알려줘


== 2.5 COM(Common Object Model)

== 2.5 Java
=== Java GC(Garbage Collection)
Default GC::
Serial GC:: 차례대로 단일 쓰레드
Parallel GC:: 다중 쓰레드
CMS GC:: Application Thread 와 GC Thread 동시 수행

== 2.6 EJB

== 2.7 WAS

== 2.8 EAI
데이터 연결 통로 확보, 데이터 공유/통합 업무 처리 시스템
* Data Level 통합
* Object Level 통합
* Process Level 통합

[cols="^2,4,4", %autowidth.stretch]
|===
^| 구분 ^| HUB & Spoke ^| Message Bus

^| 기능
a| * Hub System + Queue
a| * 미들웨어(Bus)

^| 장단점
a| * 쉬움
* Hub 죽음 다 죽음
a| * 고속전송/확장성
|===

=== TP(Transaction Processing)
Broker-based Architecture::
Bus-based Architecture::

//==

== 2.9 X-Internet

== 2.10 HTML5

== 2.11 Android

== 2.12 오픈소스
[cols="^2,<8,^1", %autowidth.stretch]
|===
^| OSS ^| 설명 ^| 강도

^| AGPL     a| 무조건 공개 | 최강
^| GPL 2.0  a| 무조건 공개 | 강
^| LGPL 2.1 a| 사용한 부분만 공개 | 중
^| BSD      a| | 하
^| Apache   a| 라이센스 및 저작관 명시 + 변경 사항 | 하
^| MPL      a| | 하
^| MIT      a| 라이센스 및 저작관 명시 | 하
|===

== 기타
HTTP Method 멱등성::
동일한 요청을 한 번 보내는 것과 여러 번 연속으로 보내는 것이 같은 효과를 지니고, 서버의 상태도 동일하게 남을 때,
해당 HTTP 메서드가 멱등성을 가졌다고 말합니다. +
다른 말로는, 멱등성 메서드에는 통계 기록 등을 제외하면 어떠한 부수 효과(side effect)도 존재해서는 안됩니다. +
올바르게 구현한 경우 GET, HEAD, PUT, DELETE 메서드는 멱등성을 가지며, POST 메서드는 그렇지 않습니다. +
모든 안전한(서버데이터 변화 없음) 메서드는 멱등성도 가집니다.

[cols="^2,^1,^1"]
|===
^| Method ^| 안전 ^| 멱등성

| HEAD      | O | O
| GET       | O | O
| POST      | X | X
| PUT/PATCH | X | O
| DELETE    | X | O
|===
